
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsyqcurippxxlsljktbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzeXFjdXJpcHB4eGxzbGprdGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTE3NDQsImV4cCI6MjA2MDI4Nzc0NH0.1JXVIuIJ_dcO85ddRHaYazyxWJ4--fWjnbxOuKvVvBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
